import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://premiumsend.uz";

  const uzPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${baseUrl}/1-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/3-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/6-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/12-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/oferta`,
      lastModified: new Date("2026-04-05"),
      changeFrequency: "yearly",
      priority: 0.5,
    },
    {
      url: `${baseUrl}/haqida`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/maqolalar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-xavfsiz-aldovdan-saqlanish`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-stars-ozbekistondan-sotib-olish`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-payme-orqali`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/3-oylik-telegram-premium-payme-orqali`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-stars-vs-telegram-premium`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-stikerlari-emoji-reaksiyalari`,
      lastModified: new Date("2026-05-06"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/6-oylik-telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-07"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-stars-click-payme-orqali-somda`,
      lastModified: new Date("2026-05-07"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/maqolalar/premiumsend-vs-boshqa-resellerlar`,
      lastModified: new Date("2026-05-07"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/nega-telegram-premium-app-store-play-market-qimmat`,
      lastModified: new Date("2026-05-08"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/6-oylik-telegram-premium-click-orqali`,
      lastModified: new Date("2026-05-09"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/6-oylik-telegram-premium-sovga-qilish`,
      lastModified: new Date("2026-05-11"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/6-oylik-telegram-premium-payme-orqali`,
      lastModified: new Date("2026-05-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-stars-uzcard-orqali`,
      lastModified: new Date("2026-05-12"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-stars-paketlari-narxlari`,
      lastModified: new Date("2026-05-13"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/12-oylik-telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-14"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-4gb-fayl-kanal-guruh-limitlari`,
      lastModified: new Date("2026-05-16"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-somda-uzs-sotib-olish`,
      lastModified: new Date("2026-05-18"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-tugilgan-kun-sovgasi`,
      lastModified: new Date("2026-05-19"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-narxlari`,
      lastModified: new Date("2026-04-30"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-stars-nima`,
      lastModified: new Date("2026-04-30"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-vs-oddiy-telegram`,
      lastModified: new Date("2026-05-02"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-02"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/3-oylik-telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-03"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-click-orqali`,
      lastModified: new Date("2026-05-03"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/3-oylik-telegram-premium-click-orqali`,
      lastModified: new Date("2026-05-03"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-qachon-faollashadi`,
      lastModified: new Date("2026-05-01"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-nima`,
      lastModified: new Date("2026-04-29"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/telegram-premium-eng-arzon-qayerdan-sotib-olish`,
      lastModified: new Date("2026-04-29"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/maqolalar/1-oylik-telegram-premium-uzcard-orqali-sotib-olish`,
      lastModified: new Date("2026-04-08"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/1-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-07"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/3-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-02"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/6-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-02"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/maqolalar/12-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-02"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
  ];

  const ruPages: MetadataRoute.Sitemap = [
    {
      url: `${baseUrl}/ru`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/ru/1-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/3-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/6-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/12-oylik`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/oferta`,
      lastModified: new Date("2026-04-05"),
      changeFrequency: "yearly",
      priority: 0.4,
    },
    {
      url: `${baseUrl}/ru/o-nas`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${baseUrl}/ru/maqolalar`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-xavfsiz-aldovdan-saqlanish`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-stars-ozbekistondan-sotib-olish`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-payme-orqali`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/3-oylik-telegram-premium-payme-orqali`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-stikerlari-emoji-reaksiyalari`,
      lastModified: new Date("2026-05-06"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/6-oylik-telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-07"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-stars-click-payme-orqali-somda`,
      lastModified: new Date("2026-05-07"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${baseUrl}/ru/maqolalar/premiumsend-vs-boshqa-resellerlar`,
      lastModified: new Date("2026-05-07"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/nega-telegram-premium-app-store-play-market-qimmat`,
      lastModified: new Date("2026-05-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/6-oylik-telegram-premium-click-orqali`,
      lastModified: new Date("2026-05-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/6-oylik-telegram-premium-sovga-qilish`,
      lastModified: new Date("2026-05-11"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/6-oylik-telegram-premium-payme-orqali`,
      lastModified: new Date("2026-05-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-stars-uzcard-orqali`,
      lastModified: new Date("2026-05-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-stars-paketlari-narxlari`,
      lastModified: new Date("2026-05-13"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/12-oylik-telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-14"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-4gb-fayl-kanal-guruh-limitlari`,
      lastModified: new Date("2026-05-16"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-somda-uzs-sotib-olish`,
      lastModified: new Date("2026-05-18"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-tugilgan-kun-sovgasi`,
      lastModified: new Date("2026-05-19"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-stars-vs-telegram-premium`,
      lastModified: new Date("2026-05-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-narxlari`,
      lastModified: new Date("2026-04-30"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-eng-arzon-qayerdan-sotib-olish`,
      lastModified: new Date("2026-04-29"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-stars-nima`,
      lastModified: new Date("2026-04-30"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-vs-oddiy-telegram`,
      lastModified: new Date("2026-05-02"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-02"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/3-oylik-telegram-premium-humo-orqali`,
      lastModified: new Date("2026-05-03"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-click-orqali`,
      lastModified: new Date("2026-05-03"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/3-oylik-telegram-premium-click-orqali`,
      lastModified: new Date("2026-05-03"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-qachon-faollashadi`,
      lastModified: new Date("2026-05-01"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/telegram-premium-nima`,
      lastModified: new Date("2026-04-29"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${baseUrl}/ru/maqolalar/1-oylik-telegram-premium-uzcard-orqali-sotib-olish`,
      lastModified: new Date("2026-04-08"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${baseUrl}/ru/maqolalar/1-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-07"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${baseUrl}/ru/maqolalar/3-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-07"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${baseUrl}/ru/maqolalar/6-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-07"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${baseUrl}/ru/maqolalar/12-oylik-telegram-premium-sotib-olish`,
      lastModified: new Date("2026-04-07"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
  ];

  return [...uzPages, ...ruPages];
}
